name: Rust Build
run-name: ${{ github.actor }} is building the files for a release 🚀
on:
  push:
    branches-ignore:
      - release

jobs:
  push:
    name: building - ${{ matrix.platform.release_for }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
#          - release_for: Windows - X86_64
#            target: x86_64-pc-windows-gnu
          - release_for: Linux - X86_64
            target: x86_64-unknown-linux-musl
#          - release_for: FreeBSD - x86_64
#            target: x86_64-unknown-freebsd
#          - release_for: Mac - X86_64
#            target: x86_64-apple-darwin
#          - release_for: Mac - ARM
#            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
